# Generated by Django 4.0 on 2021-12-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Geners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GenersOfMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.geners')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('avg_vote', models.FloatField()),
                ('gross_income', models.IntegerField()),
                ('n_user_reviews', models.IntegerField()),
                ('n_critic_reviews', models.IntegerField()),
                ('imdb_title_id', models.IntegerField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.country')),
            ],
        ),
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('bio', models.CharField(max_length=256)),
                ('birth_details', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=128)),
                ('death_details', models.CharField(max_length=256)),
                ('date_of_death', models.DateField()),
                ('place_of_death', models.CharField(max_length=128)),
                ('spouses', models.IntegerField()),
                ('divorces', models.IntegerField()),
                ('spouses_with_children', models.IntegerField()),
                ('children', models.IntegerField()),
                ('imdb_name_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductionComp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TitlePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('category', models.CharField(max_length=128)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.movies')),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.names')),
            ],
        ),
        migrations.CreateModel(
            name='ReasonOfDeath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.geners')),
            ],
        ),
        migrations.AddField(
            model_name='names',
            name='reason_of_death_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.reasonofdeath'),
        ),
        migrations.AddField(
            model_name='movies',
            name='credits',
            field=models.ManyToManyField(through='mvpkr.TitlePrincipal', to='mvpkr.Names'),
        ),
        migrations.AddField(
            model_name='movies',
            name='generes',
            field=models.ManyToManyField(through='mvpkr.GenersOfMovies', to='mvpkr.Geners'),
        ),
        migrations.AddField(
            model_name='movies',
            name='language_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.language'),
        ),
        migrations.AddField(
            model_name='movies',
            name='prod_company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.productioncomp'),
        ),
        migrations.AddField(
            model_name='genersofmovies',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvpkr.movies'),
        ),
    ]
