# Generated by Django 4.0 on 2021-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpkr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasonofdeath',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
