# Generated by Django 4.0 on 2021-12-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpkr', '0002_alter_reasonofdeath_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
