# Generated by Django 4.0 on 2021-12-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvpkr', '0003_alter_names_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='names',
            name='children',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='divorces',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='spouses',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='names',
            name='spouses_with_children',
            field=models.IntegerField(null=True),
        ),
    ]
